name: versioning
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: tags
        uses: actions/github-scripts@v5
        with:
          github-token: ${{ github.token }}
        github-token: ${{ github.token }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/devd-testd-to-main",
            sha: context.sha
          })
